version: "3.9"
services:
  app:
    build: 
      context: ./
      dockerfile: ./build/package/Dockerfile
      args:
        - ENV_API_URL=http://template.natron.io/api
    ports:
      - "8090:8090"
    volumes:
      - data:/data

volumes:
  data: {}